// <auto-generated />
using DongPhuong.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DongPhuong.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240216164713_PackagedGoodsInit")]
    partial class PackagedGoodsInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DongPhuong.Domain.Entities.PackagedGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(2, 10)
                        .HasColumnType("decimal(2,10)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(2, 5)
                        .HasColumnType("decimal(2,5)");

                    b.HasKey("Id");

                    b.ToTable("System.Linq.Enumerable+AppendPrepend1Iterator`1[System.Char]", "Domain");
                });
#pragma warning restore 612, 618
        }
    }
}
