name: Build and deploy ASP.Net Core app to Azure Web App - dong-phuong-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore ./src/Presentation/Presentation.csproj

      - name: Build the project
        run: dotnet build ./src/Presentation/Presentation.csproj --no-restore --configuration Release

      - name: Publish the project
        run: dotnet publish ./src/Presentation/Presentation.csproj --no-build --configuration Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_39147396A3E44A81A334D1F7D731481F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_051D5ED13ED54279AD0F920E90F06D65 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_41F8013772AA4C5091C22D2FDBF03A0F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "dong-phuong-api"
          package: ${{env.DOTNET_ROOT}}/myapp
