name: Web Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: List directory structure
      run: ls -R
      working-directory: web
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: web
    - name: Build
      run: npm run build
      working-directory: web
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: web/dist
